import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import {
  createMint,
  getOrCreateAssociatedTokenAccount,
  mintTo,
  getAccount,
  Account as TokenAccountInfo,
} from "@solana/spl-token";
import {
  Keypair,
  PublicKey,
  SystemProgram,
  LAMPORTS_PER_SOL,
} from "@solana/web3.js";
import { assert, expect } from "chai";

// Import the IDL type (generated by `anchor build`)
// @ts-ignore — IDL generated at build time
import { X402Guard } from "../target/types/x402_guard";

describe("x402-guard", () => {
  const provider = anchor.AnchorProvider.env();
  anchor.setProvider(provider);

  const program = anchor.workspace.X402Guard as Program<X402Guard>;
  const connection = provider.connection;

  // Test keypairs
  const owner = Keypair.generate();
  const agent = Keypair.generate();
  const nonOwner = Keypair.generate();
  const destinationOwner = Keypair.generate();

  // USDC mock mint (6 decimals)
  let usdcMint: PublicKey;
  const USDC_DECIMALS = 6;
  const ONE_USDC = 1_000_000; // 1 USDC in lamports (6 decimals)

  // Vault PDA
  let vaultPda: PublicKey;
  let vaultBump: number;

  // Token accounts
  let ownerAta: TokenAccountInfo;
  let vaultAta: TokenAccountInfo;
  let destinationAta: TokenAccountInfo;
  let agentAta: TokenAccountInfo;

  // Whitelisted program for testing
  const whitelistedProgram = Keypair.generate().publicKey;

  before(async () => {
    // Airdrop SOL to test accounts
    const airdropPromises = [owner, agent, nonOwner, destinationOwner].map(
      async (kp) => {
        const sig = await connection.requestAirdrop(
          kp.publicKey,
          10 * LAMPORTS_PER_SOL
        );
        await connection.confirmTransaction(sig, "confirmed");
      }
    );
    await Promise.all(airdropPromises);

    // Create mock USDC mint (owner is mint authority)
    usdcMint = await createMint(
      connection,
      owner,
      owner.publicKey,
      null,
      USDC_DECIMALS
    );

    // Derive vault PDA
    [vaultPda, vaultBump] = PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), owner.publicKey.toBuffer()],
      program.programId
    );

    // Create ATAs
    ownerAta = await getOrCreateAssociatedTokenAccount(
      connection,
      owner,
      usdcMint,
      owner.publicKey
    );

    destinationAta = await getOrCreateAssociatedTokenAccount(
      connection,
      destinationOwner,
      usdcMint,
      destinationOwner.publicKey
    );

    agentAta = await getOrCreateAssociatedTokenAccount(
      connection,
      agent,
      usdcMint,
      agent.publicKey
    );

    // Mint USDC to owner for deposits
    await mintTo(
      connection,
      owner,
      usdcMint,
      ownerAta.address,
      owner,
      1000 * ONE_USDC // 1000 USDC
    );
  });

  // ---- Test 1: Initialize vault with valid params ----
  it("1. Initialize vault with valid params", async () => {
    const tx = await program.methods
      .initializeVault({
        agent: agent.publicKey,
        maxSpendPerTx: new anchor.BN(100 * ONE_USDC),
        maxSpendPerDay: new anchor.BN(500 * ONE_USDC),
        agentExpiresAt: new anchor.BN(0), // no expiry
        allowedPrograms: [],
      })
      .accounts({
        owner: owner.publicKey,
        usdcMint: usdcMint,
      })
      .signers([owner])
      .rpc();

    // Verify vault state
    const vault = await program.account.vaultState.fetch(vaultPda);
    assert.ok(vault.owner.equals(owner.publicKey));
    assert.ok(vault.agent.equals(agent.publicKey));
    assert.equal(vault.maxSpendPerTx.toNumber(), 100 * ONE_USDC);
    assert.equal(vault.maxSpendPerDay.toNumber(), 500 * ONE_USDC);
    assert.equal(vault.spentToday.toNumber(), 0);
    assert.equal(vault.agentExpiresAt.toNumber(), 0);
    assert.deepEqual(vault.allowedPrograms, []);
    assert.equal(vault.isActive, true);
    assert.equal(vault.bump, vaultBump);
  });

  // ---- Test 2: Deposit USDC ----
  it("2. Deposit USDC — vault balance increases", async () => {
    // Get vault ATA (created during initialize_vault)
    vaultAta = await getOrCreateAssociatedTokenAccount(
      connection,
      owner,
      usdcMint,
      vaultPda,
      true // allowOwnerOffCurve for PDA
    );

    const depositAmount = 200 * ONE_USDC;

    await program.methods
      .deposit(new anchor.BN(depositAmount))
      .accounts({
        depositor: owner.publicKey,
        vault: vaultPda,
        depositorTokenAccount: ownerAta.address,
        vaultTokenAccount: vaultAta.address,
        usdcMint: usdcMint,
      })
      .signers([owner])
      .rpc();

    // Verify vault balance
    const vaultBalance = await getAccount(connection, vaultAta.address);
    assert.equal(Number(vaultBalance.amount), depositAmount);
  });

  // ---- Test 3: Guarded withdraw within limits ----
  it("3. Guarded withdraw within limits — success, spent_today updated", async () => {
    const withdrawAmount = 50 * ONE_USDC;

    await program.methods
      .guardedWithdraw(new anchor.BN(withdrawAmount))
      .accounts({
        agent: agent.publicKey,
        vault: vaultPda,
        vaultTokenAccount: vaultAta.address,
        destinationTokenAccount: destinationAta.address,
        usdcMint: usdcMint,
      })
      .signers([agent])
      .rpc();

    // Verify vault state updated
    const vault = await program.account.vaultState.fetch(vaultPda);
    assert.equal(vault.spentToday.toNumber(), withdrawAmount);

    // Verify destination received funds
    const destBalance = await getAccount(connection, destinationAta.address);
    assert.equal(Number(destBalance.amount), withdrawAmount);
  });

  // ---- Test 4: Withdraw exceeding per-tx limit ----
  it("4. Guarded withdraw exceeding per-tx limit — error", async () => {
    const tooLargeAmount = 150 * ONE_USDC; // limit is 100 USDC

    try {
      await program.methods
        .guardedWithdraw(new anchor.BN(tooLargeAmount))
        .accounts({
          agent: agent.publicKey,
          vault: vaultPda,
          vaultTokenAccount: vaultAta.address,
          destinationTokenAccount: destinationAta.address,
          usdcMint: usdcMint,
        })
        .signers([agent])
        .rpc();
      assert.fail("Should have thrown ExceedsPerTxLimit");
    } catch (err: any) {
      assert.include(err.toString(), "ExceedsPerTxLimit");
    }
  });

  // ---- Test 5: Withdraw exceeding daily cap ----
  it("5. Guarded withdraw exceeding daily cap — error", async () => {
    // Already spent 50 USDC. Daily cap is 500 USDC. Try to spend 460 to exceed.
    const pushToDailyCapAmount = 460 * ONE_USDC;

    try {
      await program.methods
        .guardedWithdraw(new anchor.BN(pushToDailyCapAmount))
        .accounts({
          agent: agent.publicKey,
          vault: vaultPda,
          vaultTokenAccount: vaultAta.address,
          destinationTokenAccount: destinationAta.address,
          usdcMint: usdcMint,
        })
        .signers([agent])
        .rpc();
      assert.fail("Should have thrown ExceedsDailyCap");
    } catch (err: any) {
      // Could be ExceedsDailyCap or ExceedsPerTxLimit (460 > 100 per-tx)
      const errStr = err.toString();
      assert.ok(
        errStr.includes("ExceedsDailyCap") ||
          errStr.includes("ExceedsPerTxLimit"),
        `Expected daily cap or per-tx error, got: ${errStr}`
      );
    }
  });

  // ---- Test 6: Withdraw to non-whitelisted destination ----
  it("6. Guarded withdraw to non-whitelisted destination — error", async () => {
    // First, update rules to add a whitelist
    await program.methods
      .updateRules({
        newMaxSpendPerTx: null,
        newMaxSpendPerDay: null,
        newAllowedPrograms: [whitelistedProgram],
        newAgent: null,
        newAgentExpiresAt: null,
        newIsActive: null,
      })
      .accounts({
        owner: owner.publicKey,
        vault: vaultPda,
      })
      .signers([owner])
      .rpc();

    // Now try withdraw — destination owner is NOT whitelisted
    try {
      await program.methods
        .guardedWithdraw(new anchor.BN(10 * ONE_USDC))
        .accounts({
          agent: agent.publicKey,
          vault: vaultPda,
          vaultTokenAccount: vaultAta.address,
          destinationTokenAccount: destinationAta.address,
          usdcMint: usdcMint,
        })
        .signers([agent])
        .rpc();
      assert.fail("Should have thrown ProgramNotWhitelisted");
    } catch (err: any) {
      assert.include(err.toString(), "ProgramNotWhitelisted");
    }

    // Clean up: remove whitelist for subsequent tests
    await program.methods
      .updateRules({
        newMaxSpendPerTx: null,
        newMaxSpendPerDay: null,
        newAllowedPrograms: [],
        newAgent: null,
        newAgentExpiresAt: null,
        newIsActive: null,
      })
      .accounts({
        owner: owner.publicKey,
        vault: vaultPda,
      })
      .signers([owner])
      .rpc();
  });

  // ---- Test 7: Withdraw with expired agent ----
  it("7. Guarded withdraw with expired agent — error", async () => {
    // Set agent expiry to past timestamp
    const pastTimestamp = Math.floor(Date.now() / 1000) - 3600; // 1 hour ago

    await program.methods
      .updateRules({
        newMaxSpendPerTx: null,
        newMaxSpendPerDay: null,
        newAllowedPrograms: null,
        newAgent: null,
        newAgentExpiresAt: new anchor.BN(pastTimestamp),
        newIsActive: null,
      })
      .accounts({
        owner: owner.publicKey,
        vault: vaultPda,
      })
      .signers([owner])
      .rpc();

    try {
      await program.methods
        .guardedWithdraw(new anchor.BN(10 * ONE_USDC))
        .accounts({
          agent: agent.publicKey,
          vault: vaultPda,
          vaultTokenAccount: vaultAta.address,
          destinationTokenAccount: destinationAta.address,
          usdcMint: usdcMint,
        })
        .signers([agent])
        .rpc();
      assert.fail("Should have thrown AgentExpired");
    } catch (err: any) {
      assert.include(err.toString(), "AgentExpired");
    }

    // Clean up: remove expiry
    await program.methods
      .updateRules({
        newMaxSpendPerTx: null,
        newMaxSpendPerDay: null,
        newAllowedPrograms: null,
        newAgent: null,
        newAgentExpiresAt: new anchor.BN(0),
        newIsActive: null,
      })
      .accounts({
        owner: owner.publicKey,
        vault: vaultPda,
      })
      .signers([owner])
      .rpc();
  });

  // ---- Test 8: Withdraw after revoke ----
  it("8. Guarded withdraw after revoke — error (agent = default)", async () => {
    // Revoke the agent
    await program.methods
      .revokeAgent()
      .accounts({
        owner: owner.publicKey,
        vault: vaultPda,
      })
      .signers([owner])
      .rpc();

    // Verify vault state
    const vault = await program.account.vaultState.fetch(vaultPda);
    assert.ok(vault.agent.equals(PublicKey.default));
    assert.equal(vault.isActive, false);

    // Try to withdraw — should fail (vault paused AND agent mismatched)
    try {
      await program.methods
        .guardedWithdraw(new anchor.BN(10 * ONE_USDC))
        .accounts({
          agent: agent.publicKey,
          vault: vaultPda,
          vaultTokenAccount: vaultAta.address,
          destinationTokenAccount: destinationAta.address,
          usdcMint: usdcMint,
        })
        .signers([agent])
        .rpc();
      assert.fail("Should have thrown VaultPaused or Unauthorized");
    } catch (err: any) {
      const errStr = err.toString();
      assert.ok(
        errStr.includes("VaultPaused") || errStr.includes("Unauthorized"),
        `Expected pause/auth error, got: ${errStr}`
      );
    }

    // Restore agent for subsequent tests
    await program.methods
      .updateRules({
        newMaxSpendPerTx: null,
        newMaxSpendPerDay: null,
        newAllowedPrograms: null,
        newAgent: agent.publicKey,
        newAgentExpiresAt: null,
        newIsActive: true,
      })
      .accounts({
        owner: owner.publicKey,
        vault: vaultPda,
      })
      .signers([owner])
      .rpc();
  });

  // ---- Test 9: Update rules (owner) ----
  it("9. Update rules (owner) — success", async () => {
    const newPerTx = 200 * ONE_USDC;
    const newPerDay = 1000 * ONE_USDC;

    await program.methods
      .updateRules({
        newMaxSpendPerTx: new anchor.BN(newPerTx),
        newMaxSpendPerDay: new anchor.BN(newPerDay),
        newAllowedPrograms: null,
        newAgent: null,
        newAgentExpiresAt: null,
        newIsActive: null,
      })
      .accounts({
        owner: owner.publicKey,
        vault: vaultPda,
      })
      .signers([owner])
      .rpc();

    const vault = await program.account.vaultState.fetch(vaultPda);
    assert.equal(vault.maxSpendPerTx.toNumber(), newPerTx);
    assert.equal(vault.maxSpendPerDay.toNumber(), newPerDay);
  });

  // ---- Test 10: Update rules (non-owner) ----
  it("10. Update rules (non-owner) — error", async () => {
    try {
      await program.methods
        .updateRules({
          newMaxSpendPerTx: new anchor.BN(999 * ONE_USDC),
          newMaxSpendPerDay: new anchor.BN(9999 * ONE_USDC),
          newAllowedPrograms: null,
          newAgent: null,
          newAgentExpiresAt: null,
          newIsActive: null,
        })
        .accounts({
          owner: nonOwner.publicKey,
          vault: vaultPda,
        })
        .signers([nonOwner])
        .rpc();
      assert.fail("Should have thrown Unauthorized");
    } catch (err: any) {
      // Anchor has_one constraint returns ConstraintHasOne or custom error
      const errStr = err.toString();
      assert.ok(
        errStr.includes("Unauthorized") ||
          errStr.includes("has_one") ||
          errStr.includes("ConstraintHasOne") ||
          errStr.includes("2012") || // ConstraintHasOne error code
          errStr.includes("A has one constraint was violated"),
        `Expected authorization error, got: ${errStr}`
      );
    }
  });

  // ---- Test 11: Revoke agent — state verification ----
  it("11. Revoke agent — agent zeroed, vault paused", async () => {
    // First ensure agent is set
    let vault = await program.account.vaultState.fetch(vaultPda);
    assert.ok(vault.agent.equals(agent.publicKey));
    assert.equal(vault.isActive, true);

    // Revoke
    await program.methods
      .revokeAgent()
      .accounts({
        owner: owner.publicKey,
        vault: vaultPda,
      })
      .signers([owner])
      .rpc();

    // Verify
    vault = await program.account.vaultState.fetch(vaultPda);
    assert.ok(vault.agent.equals(PublicKey.default));
    assert.equal(vault.isActive, false);
    assert.equal(vault.agentExpiresAt.toNumber(), 0);

    // Restore for close_vault test
    await program.methods
      .updateRules({
        newMaxSpendPerTx: null,
        newMaxSpendPerDay: null,
        newAllowedPrograms: null,
        newAgent: agent.publicKey,
        newAgentExpiresAt: null,
        newIsActive: true,
      })
      .accounts({
        owner: owner.publicKey,
        vault: vaultPda,
      })
      .signers([owner])
      .rpc();
  });

  // ---- Test 12: Close vault ----
  it("12. Close vault — USDC returned, accounts closed", async () => {
    // Record balances before close
    const vaultBalanceBefore = await getAccount(connection, vaultAta.address);
    const ownerBalanceBefore = await getAccount(connection, ownerAta.address);
    const vaultUsdcBefore = Number(vaultBalanceBefore.amount);

    // Close vault
    await program.methods
      .closeVault()
      .accounts({
        owner: owner.publicKey,
        vault: vaultPda,
        vaultTokenAccount: vaultAta.address,
        ownerTokenAccount: ownerAta.address,
        usdcMint: usdcMint,
      })
      .signers([owner])
      .rpc();

    // Verify owner received USDC
    const ownerBalanceAfter = await getAccount(connection, ownerAta.address);
    const expectedOwnerBalance =
      Number(ownerBalanceBefore.amount) + vaultUsdcBefore;
    assert.equal(Number(ownerBalanceAfter.amount), expectedOwnerBalance);

    // Verify vault PDA is closed
    try {
      await program.account.vaultState.fetch(vaultPda);
      assert.fail("Vault should be closed");
    } catch (err: any) {
      // Account should not exist
      assert.ok(
        err.toString().includes("Account does not exist") ||
          err.toString().includes("Could not find"),
        `Expected account-not-found error, got: ${err.toString()}`
      );
    }
  });

  // ---- Test 13: Daily window reset after 24h ----
  // NOTE: This test requires Clock manipulation which is only available
  // in programs-test (Rust). In Anchor TS tests on localnet, we document
  // the expected behavior and test the logic indirectly.
  it("13. Daily window reset — documented (requires Clock warp for full test)", async () => {
    // Re-initialize vault for this test
    const tx = await program.methods
      .initializeVault({
        agent: agent.publicKey,
        maxSpendPerTx: new anchor.BN(100 * ONE_USDC),
        maxSpendPerDay: new anchor.BN(200 * ONE_USDC),
        agentExpiresAt: new anchor.BN(0),
        allowedPrograms: [],
      })
      .accounts({
        owner: owner.publicKey,
        usdcMint: usdcMint,
      })
      .signers([owner])
      .rpc();

    // Re-create vault ATA reference
    vaultAta = await getOrCreateAssociatedTokenAccount(
      connection,
      owner,
      usdcMint,
      vaultPda,
      true
    );

    // Deposit for testing
    await program.methods
      .deposit(new anchor.BN(500 * ONE_USDC))
      .accounts({
        depositor: owner.publicKey,
        vault: vaultPda,
        depositorTokenAccount: ownerAta.address,
        vaultTokenAccount: vaultAta.address,
        usdcMint: usdcMint,
      })
      .signers([owner])
      .rpc();

    // Spend up to daily limit (2 transactions of 100 USDC each)
    await program.methods
      .guardedWithdraw(new anchor.BN(100 * ONE_USDC))
      .accounts({
        agent: agent.publicKey,
        vault: vaultPda,
        vaultTokenAccount: vaultAta.address,
        destinationTokenAccount: destinationAta.address,
        usdcMint: usdcMint,
      })
      .signers([agent])
      .rpc();

    await program.methods
      .guardedWithdraw(new anchor.BN(100 * ONE_USDC))
      .accounts({
        agent: agent.publicKey,
        vault: vaultPda,
        vaultTokenAccount: vaultAta.address,
        destinationTokenAccount: destinationAta.address,
        usdcMint: usdcMint,
      })
      .signers([agent])
      .rpc();

    // Verify spent_today = 200 USDC
    let vault = await program.account.vaultState.fetch(vaultPda);
    assert.equal(vault.spentToday.toNumber(), 200 * ONE_USDC);

    // Attempting another withdrawal should fail (daily cap reached)
    try {
      await program.methods
        .guardedWithdraw(new anchor.BN(1 * ONE_USDC))
        .accounts({
          agent: agent.publicKey,
          vault: vaultPda,
          vaultTokenAccount: vaultAta.address,
          destinationTokenAccount: destinationAta.address,
          usdcMint: usdcMint,
        })
        .signers([agent])
        .rpc();
      assert.fail("Should have thrown ExceedsDailyCap");
    } catch (err: any) {
      assert.include(err.toString(), "ExceedsDailyCap");
    }

    // NOTE: On localnet, we cannot warp the Clock to test the 24h reset.
    // The daily reset logic in guarded_withdraw checks:
    //   if (now - day_window_start >= 86400) { spent_today = 0; day_window_start = now; }
    // This is verified by the Rust unit test structure and code review.
    // A full programs-test in Rust would use `context.warp_to_slot()` to advance time.

    // Clean up: close vault
    await program.methods
      .closeVault()
      .accounts({
        owner: owner.publicKey,
        vault: vaultPda,
        vaultTokenAccount: vaultAta.address,
        ownerTokenAccount: ownerAta.address,
        usdcMint: usdcMint,
      })
      .signers([owner])
      .rpc();
  });
});
